{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8dac261f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import datetime, timezone\n",
    "a = '2025-04-01'\n",
    "transaction_date = datetime.strptime(a, '%Y-%m-%d')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "77a7de7d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "datetime.datetime(2025, 4, 1, 0, 0, tzinfo=datetime.timezone.utc)"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "transaction_date.replace(tzinfo=timezone.utc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "4cc2e2ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker\n",
    "from sqlalchemy.orm import DeclarativeBase\n",
    "\n",
    "DATABASE_URL = \"postgresql+asyncpg://cost_project_user:6796976@localhost/cost_project_db\"\n",
    "\n",
    "engine = create_async_engine(DATABASE_URL, echo=True)\n",
    "\n",
    "async_session_maker = async_sessionmaker(engine, expire_on_commit=False)\n",
    "\n",
    "class Base(DeclarativeBase):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "d0f834e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import String, func\n",
    "from sqlalchemy.orm import Mapped, mapped_column\n",
    "from typing import Annotated\n",
    "from datetime import datetime\n",
    "\n",
    "int_pk = Annotated[int, mapped_column(primary_key=True)]\n",
    "str_255 = Annotated[str, mapped_column(String(255))]\n",
    "\n",
    "class Costs(Base):\n",
    "    __tablename__ = 'costs'\n",
    "\n",
    "    transaction_id: Mapped[int_pk]\n",
    "    user: Mapped[str_255]\n",
    "    category: Mapped[str_255]\n",
    "    description: Mapped[str_255]\n",
    "    cost: Mapped[int]\n",
    "    transaction_dttm: Mapped[datetime]\n",
    "    updated_dttm: Mapped[datetime] = mapped_column(server_default=func.now())\n",
    "\n",
    "    def __repr__(self):\n",
    "        return f\"<id={self.transaction_id} user={self.user} description={self.description} cost={self.cost}'>\"\n",
    "\n",
    "class LoginData(Base):\n",
    "    __tablename__ = 'login_data'\n",
    "\n",
    "    user: Mapped[str_255] = mapped_column(primary_key=True)\n",
    "    pass_md5: Mapped[str_255]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "7a4d4684",
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "asyncio.run() cannot be called from a running event loop",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mRuntimeError\u001b[39m                              Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[44]\u001b[39m\u001b[32m, line 12\u001b[39m\n\u001b[32m      9\u001b[39m         \u001b[38;5;28;01mawait\u001b[39;00m conn.run_sync(Base.metadata.create_all)\n\u001b[32m     10\u001b[39m         \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mТаблицы успешно созданы.\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m12\u001b[39m \u001b[43masyncio\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcreate_db_tables\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.pyenv/versions/3.12.5/lib/python3.12/asyncio/runners.py:190\u001b[39m, in \u001b[36mrun\u001b[39m\u001b[34m(main, debug, loop_factory)\u001b[39m\n\u001b[32m    161\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Execute the coroutine and return the result.\u001b[39;00m\n\u001b[32m    162\u001b[39m \n\u001b[32m    163\u001b[39m \u001b[33;03mThis function runs the passed coroutine, taking care of\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    186\u001b[39m \u001b[33;03m    asyncio.run(main())\u001b[39;00m\n\u001b[32m    187\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m    188\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m events._get_running_loop() \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    189\u001b[39m     \u001b[38;5;66;03m# fail fast with short traceback\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m190\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[32m    191\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33masyncio.run() cannot be called from a running event loop\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    193\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m Runner(debug=debug, loop_factory=loop_factory) \u001b[38;5;28;01mas\u001b[39;00m runner:\n\u001b[32m    194\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m runner.run(main)\n",
      "\u001b[31mRuntimeError\u001b[39m: asyncio.run() cannot be called from a running event loop"
     ]
    }
   ],
   "source": [
    "# create_tables.py\n",
    "\n",
    "import asyncio\n",
    "\n",
    "async def create_db_tables():\n",
    "    # async with engine.begin() установит соединение\n",
    "    async with engine.begin() as conn:\n",
    "        # Base.metadata.drop_all(conn) # Удаляет все таблицы (осторожно!)\n",
    "        await conn.run_sync(Base.metadata.create_all)\n",
    "        print(\"Таблицы успешно созданы.\")\n",
    "\n",
    "asyncio.run(create_db_tables())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "af113fa3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ://user:password@host:port/dbname\n",
    "engine = create_async_engine(\"postgresql+asyncpg:///:memory:\", echo=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "afa72fe7",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "the greenlet library is required to use this function. No module named 'greenlet'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mValueError\u001b[39m                                Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[26]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m engine.begin() \u001b[38;5;28;01mas\u001b[39;00m conn:\n\u001b[32m      2\u001b[39m     result = conn.execute(text(\u001b[33m\"\u001b[39m\u001b[33mselect \u001b[39m\u001b[33m'\u001b[39m\u001b[33mhello world\u001b[39m\u001b[33m'\u001b[39m\u001b[33m\"\u001b[39m))\n\u001b[32m      3\u001b[39m     \u001b[38;5;28mprint\u001b[39m(result.all())\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.pyenv/versions/3.12.5/lib/python3.12/contextlib.py:210\u001b[39m, in \u001b[36m_AsyncGeneratorContextManager.__aenter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    208\u001b[39m \u001b[38;5;28;01mdel\u001b[39;00m \u001b[38;5;28mself\u001b[39m.args, \u001b[38;5;28mself\u001b[39m.kwds, \u001b[38;5;28mself\u001b[39m.func\n\u001b[32m    209\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m210\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m anext(\u001b[38;5;28mself\u001b[39m.gen)\n\u001b[32m    211\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopAsyncIteration\u001b[39;00m:\n\u001b[32m    212\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mgenerator didn\u001b[39m\u001b[33m'\u001b[39m\u001b[33mt yield\u001b[39m\u001b[33m\"\u001b[39m) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/costs_project/project_venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py:1068\u001b[39m, in \u001b[36mAsyncEngine.begin\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   1053\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Return a context manager which when entered will deliver an\u001b[39;00m\n\u001b[32m   1054\u001b[39m \u001b[33;03m:class:`_asyncio.AsyncConnection` with an\u001b[39;00m\n\u001b[32m   1055\u001b[39m \u001b[33;03m:class:`_asyncio.AsyncTransaction` established.\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m   1064\u001b[39m \n\u001b[32m   1065\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m   1066\u001b[39m conn = \u001b[38;5;28mself\u001b[39m.connect()\n\u001b[32m-> \u001b[39m\u001b[32m1068\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m conn:\n\u001b[32m   1069\u001b[39m     \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m conn.begin():\n\u001b[32m   1070\u001b[39m         \u001b[38;5;28;01myield\u001b[39;00m conn\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/costs_project/project_venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py:121\u001b[39m, in \u001b[36mStartableContext.__aenter__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    120\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__aenter__\u001b[39m(\u001b[38;5;28mself\u001b[39m) -> _T_co:\n\u001b[32m--> \u001b[39m\u001b[32m121\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.start(is_ctxmanager=\u001b[38;5;28;01mTrue\u001b[39;00m)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/costs_project/project_venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py:275\u001b[39m, in \u001b[36mAsyncConnection.start\u001b[39m\u001b[34m(self, is_ctxmanager)\u001b[39m\n\u001b[32m    272\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m.sync_connection:\n\u001b[32m    273\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m exc.InvalidRequestError(\u001b[33m\"\u001b[39m\u001b[33mconnection is already started\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    274\u001b[39m \u001b[38;5;28mself\u001b[39m.sync_connection = \u001b[38;5;28mself\u001b[39m._assign_proxied(\n\u001b[32m--> \u001b[39m\u001b[32m275\u001b[39m     \u001b[38;5;28;01mawait\u001b[39;00m \u001b[43mgreenlet_spawn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43msync_engine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mconnect\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    276\u001b[39m )\n\u001b[32m    277\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/costs_project/project_venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py:101\u001b[39m, in \u001b[36mgreenlet_spawn\u001b[39m\u001b[34m(fn, *args, **kw)\u001b[39m\n\u001b[32m    100\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mgreenlet_spawn\u001b[39m(fn, *args, **kw):  \u001b[38;5;66;03m# type: ignore  # noqa: F811\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m101\u001b[39m     \u001b[43m_not_implemented\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/costs_project/project_venv/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py:81\u001b[39m, in \u001b[36m_not_implemented\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m     78\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m have_greenlet:\n\u001b[32m     79\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m81\u001b[39m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m     82\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mthe greenlet library is required to use this function.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     83\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33m \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m % greenlet_error\n\u001b[32m     84\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m greenlet_error\n\u001b[32m     85\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     86\u001b[39m )\n",
      "\u001b[31mValueError\u001b[39m: the greenlet library is required to use this function. No module named 'greenlet'"
     ]
    }
   ],
   "source": [
    "async with engine.begin() as conn:\n",
    "    result = conn.execute(text(\"select 'hello world'\"))\n",
    "    print(result.all())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f557d691",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "project_venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
